name: Build Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Rebuild native modules for Electron
        run: npm run rebuild

      - name: Build Windows installer
        run: npm run dist:win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: |
            dist/*.exe
            dist/*-portable.exe
